# Generated by Django 5.1 on 2024-08-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_options_food_add_to_week_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='add_to_week_plan',
            field=models.CharField(choices=[('WEEK1', 'Week 1'), ('WEEK2', 'Week 2'), ('WEEK3', 'Week 3'), ('WEEK4', 'Week 4')], max_length=5),
        ),
    ]
