# Generated by Django 5.1 on 2024-08-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_food_add_to_week_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_code', models.CharField(choices=[('WEEK1', 'Week 1'), ('WEEK2', 'Week 2'), ('WEEK3', 'Week 3'), ('WEEK4', 'Week 4')], max_length=5, unique=True)),
                ('week_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='add_to_week_plan',
        ),
        migrations.AddField(
            model_name='food',
            name='add_to_week_plan',
            field=models.ManyToManyField(blank=True, to='foods.weekplan'),
        ),
    ]
