# Generated by Django 5.1 on 2024-08-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_weekplan_remove_food_add_to_week_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_dairy_free',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='food',
            name='is_vegetarian',
        ),
    ]
