# Generated by Django 5.1 on 2024-08-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_remove_food_is_dairy_free_remove_food_is_vegan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekplan',
            name='week_name',
        ),
    ]
