# Generated by Django 5.1 on 2024-08-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_remove_weekplan_week_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekplan',
            name='week_code',
        ),
        migrations.AddField(
            model_name='weekplan',
            name='week',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
