# Generated by Django 5.1 on 2024-08-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_alter_weekplan_options_weekplan_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
