# Generated by Django 5.1 on 2024-08-31 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_family_group_remove_food_friendly_family_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='add_to_week_plan',
        ),
        migrations.DeleteModel(
            name='WeekPlan',
        ),
    ]
